### PR TITLE
Update version 1

### PR DESCRIPTION
**Pull request by darwyncook**
Zach,
    I am redoing the pull request, don't accept this one. Just comment on what is wrong with my code.
Dr. Cook

### CODE REVIEW

**Comment by ZachMG** [comment]
Email Needs to be validated by the following in addition to searching for an @ symbol

1) there should be a string before and after the @ symbol which cannot contain special characters (Ex: @#* etc.)
2) the adress should end in .com, .org, .edu, or .net

For Social Security:

1) length of the SSN should be 9 without '-' marks and 11 with
2) the SSN should only contain numbers
3) the SSN should be able to split into three different strings of numbers around the '-' such that the first string has a length of 3, the second a length of 2 and the third a length of 4
4) It should check to make sure the SSN has not already been taken by somebody else

For Hash:

1)make sure that the Hash is written such that the same string entered into two different instantiations of Hash will create the same hash

**Comment by darwyncook** [comment]
How about this?

import hashlib
import re


class InvalidEmail(Exception):
    pass


class InvalidSocial(Exception):
    pass


class InvalidPassword(Exception):
    pass

"""
class Email:

    def __init__(self, email):
        try:
            a, b = email.split("@")
            z = b.split(".")
            if z[-1] in ["com", "net", "edu"]:
                self.email = email
            else:
                raise InvalidEmail
        except ImportError:
            raise InvalidEmail

    def __str__(self):
        return self.email
"""

class Email:

    def __init__(self, email):
        search_Obj = re.search(r'[a-zA-Z]([a-zA-Z0-9]*)@([a-zA-Z0-9]*)\.edu|biz|com|gov', email, flags=0)
        if search_Obj is not None:
            self.email = search_Obj.group()
        else:
            raise InvalidEmail

    def __str__(self):
        return self.email


class SS:

    def __init__(self, social):
        search_Obj = re.search(r'[0-9]{3}-[0-9]{2}-[0-9]{4}', social, flags=0)
        if search_Obj is not None:
            self.social = search_Obj.group()
        else:
            raise InvalidSocial

    def __str__(self):
        return self.social


class Hash:
    def __init__(self, passwd):
        if len(passwd) > 7:
            self.hash = self.generate_hash(passwd)
        else:
            raise InvalidPassword

    def __eq__(self, other):
        if isinstance(other, str):
            return self.hash == self.generate_hash(other)
        elif isinstance(other, Hash):
            return self.hash == other.hash
        else:
            return NotImplemented

    @staticmethod
    def generate_hash(passwd):
        """ This is NOT secure, a random salt should be added"""
        return hashlib.sha512(passwd.encode("utf-8")).hexdigest()

**Comment by darwyncook** [comment]
import hashlib
import re


class InvalidEmail(Exception):
    pass


class InvalidSocial(Exception):
    pass


class InvalidPassword(Exception):
    pass


class Email:

    def __init__(self, email):
        searchobj = re.search(r'^[a-zA-Z]([a-zA-Z0-9]*)@[a-zA-Z]([a-zA-Z0-9\.]*)\.(edu|biz|com|gov)$', email, flags=0)
        if searchobj is not None:
            self.email = searchobj.group()
        else:
            raise InvalidEmail

    def __str__(self):
        return self.email


class SS:

    def __init__(self, social):
        search_obj = re.search(r'^(?!219-09-9999|078-05-1120)(?!666|000|9\d{2})\d{3}-(?!00)\d{2}-(?!0{4})\d{4}$',
                               social, flags=0)
        if search_obj is not None:
            self.social = search_obj.group()
        else:
            raise InvalidSocial

    def __str__(self):
        return self.social


class Hash:
    def __init__(self, passwd):
        if len(passwd) > 7:
            self.hash = self.generate_hash(passwd)
        else:
            raise InvalidPassword

    def __eq__(self, other):
        if isinstance(other, str):
            return self.hash == self.generate_hash(other)
        elif isinstance(other, Hash):
            return self.hash == other.hash
        else:
            return NotImplemented

    @staticmethod
    def generate_hash(passwd):
        """ This is NOT secure, a random salt should be added"""
        return hashlib.sha512(passwd.encode("utf-8")).hexdigest()

**Comment by ZachMG** [comment]
Thank you, this most recent code works well!

**Pull request merged**
